package ru.gb.mybatis.model;

public class Country {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.country_id
     *
     * @mbg.generated Tue Apr 19 21:43:39 MSK 2022
     */
    private Integer countryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.country_name
     *
     * @mbg.generated Tue Apr 19 21:43:39 MSK 2022
     */
    private String countryName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.country_id
     *
     * @return the value of country.country_id
     *
     * @mbg.generated Tue Apr 19 21:43:39 MSK 2022
     */
    public Integer getCountryId() {
        return countryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.country_id
     *
     * @param countryId the value for country.country_id
     *
     * @mbg.generated Tue Apr 19 21:43:39 MSK 2022
     */
    public void setCountryId(Integer countryId) {
        this.countryId = countryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.country_name
     *
     * @return the value of country.country_name
     *
     * @mbg.generated Tue Apr 19 21:43:39 MSK 2022
     */
    public String getCountryName() {
        return countryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.country_name
     *
     * @param countryName the value for country.country_name
     *
     * @mbg.generated Tue Apr 19 21:43:39 MSK 2022
     */
    public void setCountryName(String countryName) {
        this.countryName = countryName == null ? null : countryName.trim();
    }
}