package ru.gb.mybatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OrderStatusExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_status
     *
     * @mbg.generated Tue Apr 19 21:43:39 MSK 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_status
     *
     * @mbg.generated Tue Apr 19 21:43:39 MSK 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_status
     *
     * @mbg.generated Tue Apr 19 21:43:39 MSK 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_status
     *
     * @mbg.generated Tue Apr 19 21:43:39 MSK 2022
     */
    public OrderStatusExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_status
     *
     * @mbg.generated Tue Apr 19 21:43:39 MSK 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_status
     *
     * @mbg.generated Tue Apr 19 21:43:39 MSK 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_status
     *
     * @mbg.generated Tue Apr 19 21:43:39 MSK 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_status
     *
     * @mbg.generated Tue Apr 19 21:43:39 MSK 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_status
     *
     * @mbg.generated Tue Apr 19 21:43:39 MSK 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_status
     *
     * @mbg.generated Tue Apr 19 21:43:39 MSK 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_status
     *
     * @mbg.generated Tue Apr 19 21:43:39 MSK 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_status
     *
     * @mbg.generated Tue Apr 19 21:43:39 MSK 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_status
     *
     * @mbg.generated Tue Apr 19 21:43:39 MSK 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_status
     *
     * @mbg.generated Tue Apr 19 21:43:39 MSK 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order_status
     *
     * @mbg.generated Tue Apr 19 21:43:39 MSK 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOrderStatusIdIsNull() {
            addCriterion("order_status_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderStatusIdIsNotNull() {
            addCriterion("order_status_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderStatusIdEqualTo(String value) {
            addCriterion("order_status_id =", value, "orderStatusId");
            return (Criteria) this;
        }

        public Criteria andOrderStatusIdNotEqualTo(String value) {
            addCriterion("order_status_id <>", value, "orderStatusId");
            return (Criteria) this;
        }

        public Criteria andOrderStatusIdGreaterThan(String value) {
            addCriterion("order_status_id >", value, "orderStatusId");
            return (Criteria) this;
        }

        public Criteria andOrderStatusIdGreaterThanOrEqualTo(String value) {
            addCriterion("order_status_id >=", value, "orderStatusId");
            return (Criteria) this;
        }

        public Criteria andOrderStatusIdLessThan(String value) {
            addCriterion("order_status_id <", value, "orderStatusId");
            return (Criteria) this;
        }

        public Criteria andOrderStatusIdLessThanOrEqualTo(String value) {
            addCriterion("order_status_id <=", value, "orderStatusId");
            return (Criteria) this;
        }

        public Criteria andOrderStatusIdLike(String value) {
            addCriterion("order_status_id like", value, "orderStatusId");
            return (Criteria) this;
        }

        public Criteria andOrderStatusIdNotLike(String value) {
            addCriterion("order_status_id not like", value, "orderStatusId");
            return (Criteria) this;
        }

        public Criteria andOrderStatusIdIn(List<String> values) {
            addCriterion("order_status_id in", values, "orderStatusId");
            return (Criteria) this;
        }

        public Criteria andOrderStatusIdNotIn(List<String> values) {
            addCriterion("order_status_id not in", values, "orderStatusId");
            return (Criteria) this;
        }

        public Criteria andOrderStatusIdBetween(String value1, String value2) {
            addCriterion("order_status_id between", value1, value2, "orderStatusId");
            return (Criteria) this;
        }

        public Criteria andOrderStatusIdNotBetween(String value1, String value2) {
            addCriterion("order_status_id not between", value1, value2, "orderStatusId");
            return (Criteria) this;
        }

        public Criteria andUpdateAtIsNull() {
            addCriterion("update_at is null");
            return (Criteria) this;
        }

        public Criteria andUpdateAtIsNotNull() {
            addCriterion("update_at is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateAtEqualTo(Date value) {
            addCriterion("update_at =", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtNotEqualTo(Date value) {
            addCriterion("update_at <>", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtGreaterThan(Date value) {
            addCriterion("update_at >", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtGreaterThanOrEqualTo(Date value) {
            addCriterion("update_at >=", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtLessThan(Date value) {
            addCriterion("update_at <", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtLessThanOrEqualTo(Date value) {
            addCriterion("update_at <=", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtIn(List<Date> values) {
            addCriterion("update_at in", values, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtNotIn(List<Date> values) {
            addCriterion("update_at not in", values, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtBetween(Date value1, Date value2) {
            addCriterion("update_at between", value1, value2, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtNotBetween(Date value1, Date value2) {
            addCriterion("update_at not between", value1, value2, "updateAt");
            return (Criteria) this;
        }

        public Criteria andSaleIdIsNull() {
            addCriterion("sale_id is null");
            return (Criteria) this;
        }

        public Criteria andSaleIdIsNotNull() {
            addCriterion("sale_id is not null");
            return (Criteria) this;
        }

        public Criteria andSaleIdEqualTo(String value) {
            addCriterion("sale_id =", value, "saleId");
            return (Criteria) this;
        }

        public Criteria andSaleIdNotEqualTo(String value) {
            addCriterion("sale_id <>", value, "saleId");
            return (Criteria) this;
        }

        public Criteria andSaleIdGreaterThan(String value) {
            addCriterion("sale_id >", value, "saleId");
            return (Criteria) this;
        }

        public Criteria andSaleIdGreaterThanOrEqualTo(String value) {
            addCriterion("sale_id >=", value, "saleId");
            return (Criteria) this;
        }

        public Criteria andSaleIdLessThan(String value) {
            addCriterion("sale_id <", value, "saleId");
            return (Criteria) this;
        }

        public Criteria andSaleIdLessThanOrEqualTo(String value) {
            addCriterion("sale_id <=", value, "saleId");
            return (Criteria) this;
        }

        public Criteria andSaleIdLike(String value) {
            addCriterion("sale_id like", value, "saleId");
            return (Criteria) this;
        }

        public Criteria andSaleIdNotLike(String value) {
            addCriterion("sale_id not like", value, "saleId");
            return (Criteria) this;
        }

        public Criteria andSaleIdIn(List<String> values) {
            addCriterion("sale_id in", values, "saleId");
            return (Criteria) this;
        }

        public Criteria andSaleIdNotIn(List<String> values) {
            addCriterion("sale_id not in", values, "saleId");
            return (Criteria) this;
        }

        public Criteria andSaleIdBetween(String value1, String value2) {
            addCriterion("sale_id between", value1, value2, "saleId");
            return (Criteria) this;
        }

        public Criteria andSaleIdNotBetween(String value1, String value2) {
            addCriterion("sale_id not between", value1, value2, "saleId");
            return (Criteria) this;
        }

        public Criteria andStatusNameIdIsNull() {
            addCriterion("status_name_id is null");
            return (Criteria) this;
        }

        public Criteria andStatusNameIdIsNotNull() {
            addCriterion("status_name_id is not null");
            return (Criteria) this;
        }

        public Criteria andStatusNameIdEqualTo(Integer value) {
            addCriterion("status_name_id =", value, "statusNameId");
            return (Criteria) this;
        }

        public Criteria andStatusNameIdNotEqualTo(Integer value) {
            addCriterion("status_name_id <>", value, "statusNameId");
            return (Criteria) this;
        }

        public Criteria andStatusNameIdGreaterThan(Integer value) {
            addCriterion("status_name_id >", value, "statusNameId");
            return (Criteria) this;
        }

        public Criteria andStatusNameIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("status_name_id >=", value, "statusNameId");
            return (Criteria) this;
        }

        public Criteria andStatusNameIdLessThan(Integer value) {
            addCriterion("status_name_id <", value, "statusNameId");
            return (Criteria) this;
        }

        public Criteria andStatusNameIdLessThanOrEqualTo(Integer value) {
            addCriterion("status_name_id <=", value, "statusNameId");
            return (Criteria) this;
        }

        public Criteria andStatusNameIdIn(List<Integer> values) {
            addCriterion("status_name_id in", values, "statusNameId");
            return (Criteria) this;
        }

        public Criteria andStatusNameIdNotIn(List<Integer> values) {
            addCriterion("status_name_id not in", values, "statusNameId");
            return (Criteria) this;
        }

        public Criteria andStatusNameIdBetween(Integer value1, Integer value2) {
            addCriterion("status_name_id between", value1, value2, "statusNameId");
            return (Criteria) this;
        }

        public Criteria andStatusNameIdNotBetween(Integer value1, Integer value2) {
            addCriterion("status_name_id not between", value1, value2, "statusNameId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order_status
     *
     * @mbg.generated do_not_delete_during_merge Tue Apr 19 21:43:39 MSK 2022
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order_status
     *
     * @mbg.generated Tue Apr 19 21:43:39 MSK 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}