package ru.gb.mybatis.model;

import java.math.BigDecimal;
import java.util.Date;

public class Sale {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale.sale_id
     *
     * @mbg.generated Tue Apr 19 21:43:39 MSK 2022
     */
    private String saleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale.amount
     *
     * @mbg.generated Tue Apr 19 21:43:39 MSK 2022
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale.date_sale
     *
     * @mbg.generated Tue Apr 19 21:43:39 MSK 2022
     */
    private Date dateSale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale.product_id
     *
     * @mbg.generated Tue Apr 19 21:43:39 MSK 2022
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale.user_id
     *
     * @mbg.generated Tue Apr 19 21:43:39 MSK 2022
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale.store_id
     *
     * @mbg.generated Tue Apr 19 21:43:39 MSK 2022
     */
    private Integer storeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale.sale_id
     *
     * @return the value of sale.sale_id
     *
     * @mbg.generated Tue Apr 19 21:43:39 MSK 2022
     */
    public String getSaleId() {
        return saleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale.sale_id
     *
     * @param saleId the value for sale.sale_id
     *
     * @mbg.generated Tue Apr 19 21:43:39 MSK 2022
     */
    public void setSaleId(String saleId) {
        this.saleId = saleId == null ? null : saleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale.amount
     *
     * @return the value of sale.amount
     *
     * @mbg.generated Tue Apr 19 21:43:39 MSK 2022
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale.amount
     *
     * @param amount the value for sale.amount
     *
     * @mbg.generated Tue Apr 19 21:43:39 MSK 2022
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale.date_sale
     *
     * @return the value of sale.date_sale
     *
     * @mbg.generated Tue Apr 19 21:43:39 MSK 2022
     */
    public Date getDateSale() {
        return dateSale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale.date_sale
     *
     * @param dateSale the value for sale.date_sale
     *
     * @mbg.generated Tue Apr 19 21:43:39 MSK 2022
     */
    public void setDateSale(Date dateSale) {
        this.dateSale = dateSale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale.product_id
     *
     * @return the value of sale.product_id
     *
     * @mbg.generated Tue Apr 19 21:43:39 MSK 2022
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale.product_id
     *
     * @param productId the value for sale.product_id
     *
     * @mbg.generated Tue Apr 19 21:43:39 MSK 2022
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale.user_id
     *
     * @return the value of sale.user_id
     *
     * @mbg.generated Tue Apr 19 21:43:39 MSK 2022
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale.user_id
     *
     * @param userId the value for sale.user_id
     *
     * @mbg.generated Tue Apr 19 21:43:39 MSK 2022
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale.store_id
     *
     * @return the value of sale.store_id
     *
     * @mbg.generated Tue Apr 19 21:43:39 MSK 2022
     */
    public Integer getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale.store_id
     *
     * @param storeId the value for sale.store_id
     *
     * @mbg.generated Tue Apr 19 21:43:39 MSK 2022
     */
    public void setStoreId(Integer storeId) {
        this.storeId = storeId;
    }
}