package ru.gb.mybatis.model;

public class StatusName {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column status_name.status_name_id
     *
     * @mbg.generated Tue Apr 19 21:43:39 MSK 2022
     */
    private Integer statusNameId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column status_name.status_name
     *
     * @mbg.generated Tue Apr 19 21:43:39 MSK 2022
     */
    private String statusName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column status_name.status_name_id
     *
     * @return the value of status_name.status_name_id
     *
     * @mbg.generated Tue Apr 19 21:43:39 MSK 2022
     */
    public Integer getStatusNameId() {
        return statusNameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column status_name.status_name_id
     *
     * @param statusNameId the value for status_name.status_name_id
     *
     * @mbg.generated Tue Apr 19 21:43:39 MSK 2022
     */
    public void setStatusNameId(Integer statusNameId) {
        this.statusNameId = statusNameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column status_name.status_name
     *
     * @return the value of status_name.status_name
     *
     * @mbg.generated Tue Apr 19 21:43:39 MSK 2022
     */
    public String getStatusName() {
        return statusName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column status_name.status_name
     *
     * @param statusName the value for status_name.status_name
     *
     * @mbg.generated Tue Apr 19 21:43:39 MSK 2022
     */
    public void setStatusName(String statusName) {
        this.statusName = statusName == null ? null : statusName.trim();
    }
}